[package]
name = "Axelar"
version = "0.0.1"
published-at = "0xab9802a35a6f617a3ee8ffaf72dc23c966b3ff40c75329ae730025c67848e136"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
axelar = "0x0"
test = "0x0"
dummy_its = "0x0"